### ISSUE TITLE
enable interaction

### ISSUE THREAD

**Issue by KrifaYounes** [yukiasai/Gecco#13]
I want to interact with uiview added in  firstViewController with Gecco it's possible ?
like candy crush saga tutorial

**Comment by ruipfcosta** [comment]
You mean interacting with the view underneath as in [SwiftyWalkthrough](https://github.com/ruipfcosta/SwiftyWalkthrough)?

**Comment by KrifaYounes** [comment]
yes like that !
thanks ruipfcosta !

**Comment by yukiasai** [comment]
@KrifaYounes Sorry for replying late. 

With `isInsideSpotlight`, you can be determined whether you tap the erea of the spotlight.
```
optional func spotlightViewControllerTapped(viewController: SpotlightViewController, isInsideSpotlight: Bool)
```

**Comment by KrifaYounes** [comment]
@yukiasai 
i want to move a uiview above the spotlight view
thanks
