### ISSUE TITLE
carthage issue

### ISSUE THREAD

**Issue by uglyelf** [yukiasai/Gecco#20]
I'm new to Carthage, so this might be my problem but I hope not. 
When I build Carthage with `carthage update --platform iOS`
All my dependencies build fine except Gecco, which reports this error:
`*** Skipped building Gecco due to the error:
Dependency "Gecco" has no shared framework schemes for any of the platforms: iOS`
Halp!

**Comment by yukiasai** [comment]
@uglyelf Sorry for the late reply. Fixed! [0.2.1](https://github.com/yukiasai/Gecco/tree/0.2.1)
