### ISSUE TITLE
Can't support rotation?

### ISSUE THREAD

**Issue by idolx** [yukiasai/Gecco#32]
When i rotate the screen, position of the spotlight is not accurate...

**Comment by jacrax** [comment]
Have the same problem :( anyone already solve it?

**Comment by yukiasai** [comment]
Rotation isn't supported. I'll add to feature list.

**Comment by ernestofndz** [comment]
If you need to support rotation, you could fix this easily by creating a subclass of `SpotlightViewController` and override `viewWillTransition`.

```
public override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        coordinator.animate(alongsideTransition: { context in
            // do this only if you don't extend the bounds of the view as said in the next solution
            self.spotlightView.frame = CGRect(origin: CGPoint.zero, size: size) 
            
            // present spotlight
        })
}
```

Another solution would be to simply extend the size of the `spotlightView` in the delegate method `spotlightViewControllerWillPresent`. Still you would need to override `viewWillTransition` to present the spotlight at the right position, but you won't need to update the `frame`.

```
private func extendSpotlightView() {
        let size = CGSize(width: self.view.frame.width * 2, height: self.view.frame.height * 2)
        self.spotlightView.frame = CGRect(origin: .zero, size: size)
}

func spotlightViewControllerWillPresent(_ viewController: SpotlightViewController, animated: Bool) {
        self.extendSpotlightView()
        // present spotlight
}
```

**Comment by bannzai** [comment]
Try this [write](https://github.com/yukiasai/Gecco/issues/32#issuecomment-293195390) to avoid the problem. Rotational support will also be reconsidered if requested.
