### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by yoobato** [yukiasai/Gecco#35]
Need to support swift 4.0.

Line 80~83 in SportlightViewController.swift
`
fileprivate func setupTapGesture() {
        let gesture = UITapGestureRecognizer(target: self, action: #selector(SpotlightViewController.viewTapped(_:)));
        view.addGestureRecognizer(gesture)
    }
`

Need to add @objc to expose this instance method to Objective-C

**Comment by yoobato** [comment]
#36 I send a pull-request 👍

**Comment by rlam3** [comment]
@yukiasai Please upgrade to swift 4 and xcode 9. Thanks!

**Comment by yoobato** [comment]
Hmm.. is this repository stop maintaining? @yukiasai

**Comment by isseium** [comment]
+1

**Comment by alvincrisuy** [comment]
+1

**Comment by bannzai** [comment]
This PR will be closed as we have fixed [here](https://github.com/yukiasai/Gecco/pull/54). Thank you!
