### ISSUE TITLE
Unable to init `RoundedRect` with frame

### ISSUE THREAD

**Issue by markst** [yukiasai/Gecco#37]
```swift
var spotlight = Spotlight.RoundedRect.init(frame: frame)
```

**Comment by markst** [comment]
![image](https://user-images.githubusercontent.com/274318/33646577-66803800-daa4-11e7-85bc-bc5e983f48d3.png)

**Comment by bannzai** [comment]
https://github.com/yukiasai/Gecco/blob/master/Classes/Spotlight.swift#L78-L81

You can call `Spotlight.RoundedRect.init(frame: CGRect, cornerRadius: CGFloat)` for instantiate RoundedRect type.
