### ISSUE TITLE
iPhone X support?

### ISSUE THREAD

**Issue by billypchan** [yukiasai/Gecco#42]
Hi yukiasai,
I like Gecco! I have question about iPhone X support, it there any planning to solve the y-offset issue? I attached 2 snapshots from iPhone X simulator running the demo app.

![simulator screen shot - iphone x - 2018-05-19 at 13 04 17](https://user-images.githubusercontent.com/11852044/40267955-817948a8-5b65-11e8-8b3b-08d034b944e3.png)
![Uploading Simulator Screen Shot - iPhone X - 2018-05-19 at 13.04.13.png…]()

**Comment by bannzai** [comment]
This PR will be closed as we have fixed [here](https://github.com/yukiasai/Gecco/pull/55). Thank you!
