### ISSUE TITLE
How to add text in addition to spotlight?

### ISSUE THREAD

**Issue by XYHong18** [yukiasai/Gecco#50]
Hi,

I saw your demo does not only have spotlight but also text. I am wondering how to use your package to show the text?

Thanks!

**Comment by bannzai** [comment]
Gecco will support to notify each `Spotlight` move function.
So, you can implement with it. For example if you want to add label when spotlight will show, you can implement adding label with SpotlightViewDelegate for `spotlightWillAppear(spotlightView:spotlight)` .
See also: https://github.com/yukiasai/Gecco/pull/58
